### ISSUE TITLE
Scan module structs are hidden

### ISSUE THREAD

**Issue by rwygand** [rikonaka/pistol-rs#10]
Hi, not sure when or if this changed I cannot write this function:

```
fn scan() -> Result<ArpScanResults> {
    let target: Target = Target::from_subnet("192.168.0.0/24", None)?;
    let threads_num = 300;
    let timeout = Some(Duration::new(1, 5));
    let src_ipv4 = None;
    arp_scan(target, src_ipv4, threads_num, timeout)
}
```

as I cannot import pistol::scan::ArpScanResults:

```
error[E0603]: module `scan` is private
  --> src/scanner.rs:4:13
   |
4  | use pistol::scan::ArpScanResults;
   |             ^^^^ private module
   |
note: the module `scan` is defined here
  --> .../pistol-rs-575476176e5e4305/e198bc5/src/lib.rs:16:1
   |
16 | mod scan;
   | ^^^^^^^^
```

I think a pub mod scan; in lib.rs will fix it, though that may expose a lot of things you don't want to expose. If that's the case, i think you can selectively re-export the structs you'd want.

Thanks!

**Comment by rikonaka** [comment]
Hi @rwygand , I just fix that https://github.com/rikonaka/pistol-rs/commit/4a635a7fbf329e7b2713ed611a1bc4d6f106fbe5 🫣🫣🫣
