### ISSUE TITLE
windows下都扫不了吗，我记得几个月前还可以的诶

### ISSUE THREAD

**Issue by xxh396** [rikonaka/pistol-rs#13]
![image](https://github.com/user-attachments/assets/e0b6835e-8df3-4e73-ba9a-b74a60535151)

**Comment by rikonaka** [comment]
是的 😫😫😫，因为 libpnet 在 Windows 下有 bug https://github.com/libpnet/libpnet/issues/707

**Comment by xxh396** [comment]
好吧 我印象在5月份的时候，还有用你的库尝试进行syn扫描 并且是能够进行的


&nbsp;


小狂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月23日(星期二) 下午4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rikonaka/pistol-rs] windows下都扫不了吗，我记得几个月前还可以的诶 (Issue #13)














 
是的 😫😫😫，因为 libpnet 在 Windows 下有 bug libpnet/libpnet#707

**Comment by rikonaka** [comment]
Linux 和 Unix 下还是可以的 🤣🤣🤣屈尊用一下这两个系统

**Comment by rikonaka** [comment]
我看看能否将 ipv4 上的功能适配到 Windows 上，而 ipv6 上的可能还是得等上游修复

**Comment by xxh396** [comment]
那可就太好了 大佬。现在ipv4还是用得多些


小狂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rikonaka/pistol-rs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月23日(星期二) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rikonaka/pistol-rs] windows下都扫不了吗，我记得几个月前还可以的诶 (Issue #13)





 
我看看能否将 ipv4 上的功能适配到 Windows 上，而 ipv6 上的可能还是得等上游修复

**Comment by rikonaka** [comment]
改好了😂，最新的v2.0.2版本支持Windows了
