### ISSUE TITLE
Library version

### ISSUE THREAD

**Issue by don-cryptus** [rikonaka/pistol-rs#2]
Is there a non cli version?

**Comment by rikonaka** [comment]
> Is there a non cli version?

Sorry, I don't understand what you mean. postol is a library, there is no such thing as a CLI or GUI. But I have a CLI demo (https://github.com/rikonaka/pistol_cli-rs), which will be expanded in the future to become an nmap-like superset, and the GUI is not planned for the moment. 🥲🥲🥲
