### ISSUE TITLE
Specifying a network as a target?

### ISSUE THREAD

**Issue by rwygand** [rikonaka/pistol-rs#9]
Hi, great work.

I'm curious if it's possible to specify a network as a target. For example, I want to do an ARP scan of 192.168.0.1/24.

it looks like I'd have to manually construct the host list in the target. It may be useful to allow subnets to be specified?

Thanks!

**Comment by rikonaka** [comment]
Hi @rwygand , good question, to be honestly, in some previous version, I was using subnet as the input to the function, but then I realized that this was too rigid and inconsistent, so I changed to a `Target` and `Host`.

Now you can scan a subnet eaily like this:

```rust
fn test_arp_scan_subnet_new() -> Result<()> {
    let target: Target = Target::from_subnet("192.168.1.0/24", None)?;
    let threads_num = 300;
    let timeout = Some(Duration::new(1, 5));
    // let print_result = false;
    let src_ipv4 = None;
    let ret: ArpScanResults = arp_scan(target, src_ipv4, threads_num, timeout).unwrap();
    println!("{}", ret);
    Ok(())
}
 ```

**Comment by rwygand** [comment]
Ah, thank you. I was looking through the tests for Target and didn't see any that indicated that ::from_subnet existed. Thanks!.
